title: EyZEE Home
views:
- title: EyZEE Home
  theme: EyZEE Home
  path: home
  type: sections
  max_columns: 1
  sections:
  - type: grid
    cards:
    - type: tile
      name: Home
      tap_action:
        action: navigate
        navigation_path: /eyzee-main-menu/home
      entity: input_boolean.eyzee_show_welcome
      hide_state: true
      vertical: false
      color: '#D6AD60'
      icon_tap_action:
        action: navigate
        navigation_path: /eyzee-main-menu/home
