title: EyZEE Rooms
views:
- title: EyZEE Rooms
  theme: EyZEE Home
  path: rooms
  type: sections
  max_columns: 1
  sections:
  - type: grid
    cards:
    - type: markdown
      content: No rooms yet. Build your rooms to get started.
    - type: button
      name: Manage My Rooms
      tap_action:
        action: navigate
        navigation_path: /eyzee-house-builder
    - type: tile
      name: Home
      tap_action:
        action: navigate
        navigation_path: /eyzee-main-menu/home
      entity: input_boolean.eyzee_show_welcome
      hide_state: true
      vertical: false
      color: '#D6AD60'
      icon_tap_action:
        action: navigate
        navigation_path: /eyzee-main-menu/home
